name: Dependency Caching CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on every push to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- REQUIRED CACHE STEP ---
      - name: Setup Node.js (Example Dependency)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step to cache the node_modules folder
      - name: Prime the cache with key 'cache-0828b3c'
        id: cache-dependencies  # Use an ID to reference outputs
        uses: actions/cache@v4
        with:
          path: node_modules # Cache the common dependency folder
          key: cache-0828b3c
          # Note: Since the key is static, this will always be a MISS on the first run,
          # and a HIT on subsequent runs if node_modules exists.

      # Install dependencies (This step fills the cache on a MISS)
      - name: Install dependencies (npm install)
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install # Replace with your language's install command (e.g., pip install)
      
      # --- REQUIRED ECHO STEP ---
      - name: prime-cache-0828b3c
        run: |
          # The cache result is accessed via the ID and the 'cache-hit' output variable
          CACHE_STATUS=${{ steps.cache-dependencies.outputs.cache-hit }}
          if [ "$CACHE_STATUS" = "true" ]; then
            echo "Cache hit: The cache was restored successfully."
          else
            echo "Cache miss: Dependencies were installed and the cache will be saved."
          fi
          echo "Cache step succeeded: The cache step always reports success as long as it executes."
